# Date: 2024-6-12
# Author: Generated by GoCodeo.


import unittest 

from c:\Users\82057\Desktop\odrive\ODrive\tools\usr_math import divide 

class Testdivide(unittest.TestCase):

	    def test_divide_positive_numbers(self):
	        result = divide(10, 2)
	        self.assertEqual(result, 5) 


